camera:
  app:
    jwtSecret = camera-api
    jwtExpirationMs = 86400000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camera-api
    username: root
    password:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB