spring:
  datasource:
    url: jdbc:mysql://camera-db.ciw77hgxna42.us-east-1.rds.amazonaws.com:3306/camera-api
    username: admin
    password: admin123
  jpa:
    generate-ddl: false
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /camera-api